-- FindVision / ClueSight 익명 사용 통계
-- Supabase > SQL Editor에서 전체 실행

create table if not exists public.analytics_events (
    id bigint generated by default as identity primary key,
    user_id text not null,
    event_type text not null check (
        event_type in ('visit', 'image_generated')
    ),
    created_at timestamptz not null default now(),
    verification_pass boolean,
    verification_score integer,
    attempts integer
);

create index if not exists analytics_events_user_id_idx
    on public.analytics_events(user_id);

create index if not exists analytics_events_created_at_idx
    on public.analytics_events(created_at);

create index if not exists analytics_events_event_type_idx
    on public.analytics_events(event_type);

grant select, insert on table public.analytics_events to service_role;
grant usage, select on sequence public.analytics_events_id_seq to service_role;

alter table public.analytics_events enable row level security;
